# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running 'nixos-help').

{ username, hostname, ... }:

{
  imports = [
    ../../../modules/common
    ../../../modules/nixos
    ./packages.nix
    ./secure-boot.nix
    ./boot.nix
    ./networking.nix
    ./desktop.nix
    ./hardware.nix
    # Include the results of the hardware scan.
    # NOTE: This file is auto-generated by nixos-generate-config
    # Do not modify it manually - it will be overwritten
    ./hardware-configuration.nix
  ];

  #############################################################
  #
  #  Host & Users configuration
  #
  #############################################################
  networking.hostName = hostname;

  users.users.${username} = {
    home = "/home/${username}";
    description = username;
    extraGroups = [
      "networkmanager"
      "wheel"
      "podman"
    ];
    isNormalUser = true;
  };

  nix.settings.trusted-users = [ username ];

  # Auto system update (using flake)
  # Twice weekly updates (Monday and Thursday)
  system.autoUpgrade = {
    enable = true;
    flake = "/home/${username}/dotfiles/nix#kirby";
    flags = [
      "--update-input"
      "nixpkgs"
      "--update-input"
      "nixpkgs-darwin"
    ];
    dates = "Mon,Thu 04:00"; # Runs every Monday and Thursday at 04:00
    allowReboot = false;
  };

  # Set your time zone.
  time.timeZone = "America/Vancouver";
  time.hardwareClockInLocalTime = true;

  # Select internationalisation properties.
  i18n.defaultLocale = "en_CA.UTF-8";

  programs = {
    kdeconnect.enable = true;
    firefox.enable = true;
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.05"; # Did you read the comment?

}
